export const types = Object.freeze({
    SET_DRAWER: 'SET_DRAWER',
    SET_VALUE: 'SET_VALUE',
    SET_TAB_ID: 'SET_TAB_ID',
    SET_CITIES: 'SET_CITIES',
    SET_FILTERS: 'SET_FILTERS',
    SET_HISTORY_DATA: 'SET_HISTORY_DATA',
    SET_SHOW_ALL_CITIES: 'SET_SHOW_ALL_CITIES',
    SET_SENSORS_BY_CITY: 'SET_SENSORS_BY_CITY',
    SET_SHOW_ALL_SENSORS: 'SET_SHOW_ALL_SENSORS',
    SET_FORECAST_FOR_CITY: 'SET_FORECAST_FOR_CITY',
    SET_STATISTIC_FILTERS: 'SET_STATISTIC_FILTERS',
    SET_FORECAST_FOR_SENSOR: 'SET_FORECAST_FOR_SENSOR',
    SET_SENSOR_INPUT_OPTIONS: 'SET_SENSOR_INPUT_OPTIONS',
    SET_POLLUTANTS_FOR_SENSOR: 'SET_POLLUTANTS_FOR_SENSOR',
    SET_POLLUTANT_INPUT_OPTIONS: 'SET_POLLUTANT_INPUT_OPTIONS'
});