services:
  aqra-frontend:
    build:
      args:
        - BUILDKIT_PROGRESS=plain
        - NODE_ENV=${NODE_ENV:-production}
      context: ..
      dockerfile: docker/Dockerfile
    container_name: aqra-frontend
    deploy:
      replicas: 1
    env_file:
      - path: .env
        required: false
    image: aqra-frontend:latest
    networks:
      - network
    ports:
      - "8080:80"

networks:
  network:
    attachable: true
    driver: overlay